# Add ssh keys for admins
---
- name: Set up multiple authorized keys
  hosts: all
  tasks:
    - name: Set up multiple authorized keys
      authorized_key:
        user: '{{ ansible_user }}'
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "../../files/public_keys/*.pub"
